jobs: 2000
default-resources:
    - queue="shared"
    - account="mia174"
    - mem_mb="1000"
    - time="01:00:00"
    - cpus_per_task=1
cluster:
    mkdir -p logs/{rule} &&
    sbatch
        --partition={resources.queue}
        --ntasks-per-node={threads}
        --cpus-per-task={resources.cpus_per_task}
        --nodes=1
        --mem={resources.mem_mb}
        --job-name={rule}-%j
        --output=logs/{rule}/{rule}-%j.out
        --time={resources.time}
        --account={resources.account}
        --parsable
cluster-status: cluster_status.py
cluster-cancel: scancel
printshellcmds: True
latency-wait: 60 
keep-going: True
rerun-incomplete: True
retries: 1

