paths:
    basepath: /expanse/lustre/projects/mia174/jaschwa/dimerDB
    intermediates_dir: /expanse/lustre/projects/mia174/jaschwa/dimerDB/intermediates
    lib: /expanse/lustre/projects/mia174/jaschwa/dimerDB/lib
    lib_rcsb_sidechains: /expanse/lustre/projects/mia174/jaschwa/dimerDB/lib/incl_rcsb_sidechains
    tmscore_db: /expanse/lustre/projects/mia174/jaschwa/dimerDB/lib/tmdb
    contacts_db: /expanse/lustre/projects/mia174/jaschwa/dimerDB/lib/contactsdb
    seqid_db: /expanse/lustre/projects/mia174/jaschwa/dimerDB/lib/seqiddb
    out_dir: /expanse/lustre/projects/mia174/jaschwa/dimerDB/homodimerDB

exe:
    cif2pdb: /expanse/lustre/projects/mia174/jaschwa/dimerDB/bin/USalign/cif2pdb
    mmseqs: /expanse/lustre/projects/mia174/jaschwa/dimerDB/env/bin/mmseqs
    parallel: /expanse/lustre/projects/mia174/jaschwa/dimerDB/env/bin/parallel
    usalign: /expanse/lustre/projects/mia174/jaschwa/dimerDB/bin/USalign/USalign
    nwalign: /expanse/lustre/projects/mia174/jaschwa/dimerDB/bin/USalign/NWalign
    check_contact: /expanse/lustre/projects/mia174/jaschwa/dimerDB/bin/check_contact/check_contact.exe


workflow_params:
    define_contact_max_dist_angstroms: 8
    define_contact_min_num_residue_pairs: 10
    max_threads: 32
    seq_cluster_id: 90
    dimer_clustering_threshold: 0.25


subworkflow_done:
    0_local_pdb: intermediates/sub0.done         
    1_derive_dimers: intermediates/sub1.done         
    2_seq_cluster: intermediates/sub2.done         
    3_rm_structural_redundancy: intermediates/sub3.done         
    4_prep_final_data: intermediates/sub4.done         
