paths:
    basepath: /nfs/turbo/umms-zcx/jaschwa/dimerDB-dev
    intermediates_dir: /nfs/turbo/umms-zcx/jaschwa/dimerDB-dev/intermediates
    lib: /nfs/turbo/umms-zcx/jaschwa/dimerDB-dev/lib
    tmscore_db: /nfs/turbo/umms-zcx/jaschwa/dimerDB-dev/lib/tmdb
    out_dir: /nfs/turbo/umms-zcx/jaschwa/dimerDB-dev/homodimerDB

exe:
    cif2pdb: bin/USalign/cif2pdb
    mmseqs: /nfs/turbo/umms-petefred/jaschwa/HDPRED/bin/mmseqs
    usalign: bin/USalign/USalign


workflow_params:
    define_contact_max_dist_angstroms: 8
    define_contact_min_num_residue_pairs: 10
    max_threads: 32
    seq_cluster_id: 0.9
    dimer_clustering_threshold: 0.25


subworkflow_done:
    0_local_pdb: intermediates/sub0.done         
    1_derive_dimers: intermediates/sub1.done         
    2_seq_cluster: intermediates/sub2.done         
    3_rm_structural_redundancy: intermediates/sub3.done         
    4_prep_final_data: intermediates/sub4.done         
