paths:
    basepath: /nfs/turbo/umms-petefred/jaschwa/dimerDB-optimize-dev
    pipeline_files: /nfs/turbo/umms-petefred/jaschwa/dimerDB-optimize-dev/intermediates
    pdb_lib: /nfs/turbo/umms-petefred/jaschwa/dimerDB-optimize-dev/lib/chain
    pdb_tar_lib: /nfs/turbo/umms-petefred/jaschwa/dimerDB-optimize-dev/lib/tar

workflow:
    0_local_pdb_done: intermediates/sub0.done         
